### ISSUE TITLE
Make the code multi-platform

### ISSUE THREAD

**Issue by ilaborie** [d-plaindoux/actor.kotlin#1]
Most of the code does not depend on Java, and it could be interesting to use this code in native code.
<https://kotlinlang.org/docs/reference/multiplatform.html>

- by default use coroutine, and have a separated project  for ThreadPool implementation that requires JVM
- use Kotlin only collections
- use another name generator than Java UUID

The remaining issue is the replacement of Atomics in tests, maybe there is an alternative with Kotlin coroutine?

**Comment by d-plaindoux** [comment]
I initiate a new project as a multi-platform project.
